
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  IntelligentIntern\MinioStorageBundle\Service\:
    resource: '../src/Service/*'
    public: true
    tags:
      - { name: 'storage.strategy' }